/*
 * Build the single-file distributable.
 *
 * The canonical plugin body lives in `src/plugin-body.js` and is already fully
 * self-contained (no imports). This script wraps that body into `dist/plugin.js`
 * as a ready-to-paste string for Deploy DeepSeek Harness `cordis_define`
 * (`code.client`), and verifies that every module-part it depends on parses.
 *
 * Output: `dist/plugin.js` — the exact JavaScript function body to provide as
 * the `code.client` of a dynamic plugin (a single expression starting with
 * `return { ... }`).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const body = readFileSync(join(root, 'src', 'plugin-body.js'), 'utf8')

// Strip the leading block comment license header but keep the code body intact.
const cleaned = body.replace(/^\/\*[\s\S]*?\*\//, '').trim()

const banner = [
  '/*',
  ' * dsh-modal-enhancer — DISTRIBUTABLE single-file plugin body.',
  ' * Generated by scripts/build.js from src/plugin-body.js. Do not edit by hand.',
  ' *',
  ' * Paste the entire content of this file as the `code.client` of a Deploy',
  ' * DeepSeek Harness dynamic plugin (cordis_define). It must be a single JS',
  ' * function body; when the Evaluator wraps it as a function, the leading',
  ' * `return { ... }` yields the Plugin. See README.md and docs/install.md.',
  ' */',
].join('\n')

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(join(root, 'dist', 'plugin.js'), `${banner}\n${cleaned}\n`, 'utf8')
console.log('Wrote dist/plugin.js')
